# Generated by Django 3.1.3 on 2021-04-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fun_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.dog')),
            ],
        ),
    ]
