# Generated by Django 3.1.3 on 2021-04-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='good boy', max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('good_status', models.BooleanField(default=True)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('B', 'BOY'), ('G', 'GIRL')], max_length=4)),
                ('fun_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
    ]
